### ISSUE TITLE
Bluetooth olmayanlarda manuel yoklama

### ISSUE THREAD

**Issue by ozalpmurat** [qurkan43/studentattendancecontrolsystem#1]
Bugün aklıma geldi. Bluetooth yoklama aldıktan sonra, sınıfta kayıtlı olup ta telefona bilgisi gelmeyenleri listelesin ki hoca onları kendisi okuyarak **manuel yoklama** alsın. Öğrencilerin derslikte olup olmamasına göre liste elemanlarını sola ya da sağa sürükleyerekten "var" ya da "yok" olarak işaretleyebilir.

**Comment by gurkancakir** [comment]
Tamam Hocam O kısmını da yaparım. Şu anlık Arayüzlerini ve kinematiğini yapıyorum.
